// ============================================================
// data.js — All Food Data, Categories, Banners, Restaurants
// ============================================================

const CATEGORIES = [
  { id: "all",      label: "All",       icon: "🍽️" },
  { id: "veg",      label: "Veg",       icon: "🥗" },
  { id: "nonveg",   label: "Non-Veg",   icon: "🍗" },
  { id: "fastfood", label: "Fast Food", icon: "🍔" },
  { id: "desserts", label: "Desserts",  icon: "🍰" },
  { id: "beverages",label: "Beverages", icon: "🥤" },
];

const FOOD_ITEMS = [
  // ── VEG ──────────────────────────────────────────────────
  {
    id: 1,
    name: "Paneer Butter Masala",
    category: "veg",
    type: "veg",
    price: 249,
    originalPrice: 299,
    rating: 4.6,
    reviews: 2341,
    description: "Soft, fresh paneer cubes simmered in a rich, creamy tomato-based gravy infused with aromatic spices, butter, and a hint of kasuri methi. Best paired with naan or jeera rice.",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&q=80",
    restaurant: "Spice Garden",
    time: "25-30",
    tags: ["Bestseller", "Spicy"],
    calories: 380,
    badge: "Bestseller"
  },
  {
    id: 2,
    name: "Margherita Pizza",
    category: "veg",
    type: "veg",
    price: 299,
    originalPrice: 349,
    rating: 4.4,
    reviews: 1892,
    description: "Classic Italian pizza topped with fresh mozzarella cheese, ripe tomatoes, and fragrant basil leaves on a crispy thin crust baked to golden perfection in a wood-fire oven.",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&q=80",
    restaurant: "Pizza Hub",
    time: "20-25",
    tags: ["Popular"],
    calories: 620,
    badge: ""
  },
  {
    id: 3,
    name: "Veg Biryani",
    category: "veg",
    type: "veg",
    price: 199,
    originalPrice: 239,
    rating: 4.3,
    reviews: 3105,
    description: "Fragrant long-grain basmati rice layered with seasonal vegetables, whole spices, caramelized onions, and saffron milk. Served with raita and a tangy salan on the side.",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&q=80",
    restaurant: "Biryani Palace",
    time: "30-35",
    tags: ["Trending"],
    calories: 480,
    badge: "Trending"
  },
  {
    id: 4,
    name: "Dal Makhani",
    category: "veg",
    type: "veg",
    price: 179,
    originalPrice: 219,
    rating: 4.5,
    reviews: 1567,
    description: "Black lentils slow-cooked overnight on a low flame with butter, cream, and a medley of spices. A velvety, deeply flavoured North Indian classic that pairs beautifully with tandoori roti.",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&q=80",
    restaurant: "Spice Garden",
    time: "20-25",
    tags: ["Must Try"],
    calories: 340,
    badge: ""
  },
  {
    id: 5,
    name: "Palak Paneer",
    category: "veg",
    type: "veg",
    price: 229,
    originalPrice: 269,
    rating: 4.4,
    reviews: 989,
    description: "Cottage cheese cubes nestled in a smooth, vibrant spinach gravy spiced with garlic, ginger, and green chillies. A wholesome, iron-rich dish served hot with butter naan.",
    image: "https://images.unsplash.com/photo-1618449840665-9ed506d73a34?w=400&q=80",
    restaurant: "Green Bowl",
    time: "20-25",
    tags: ["Healthy"],
    calories: 310,
    badge: "Healthy"
  },

  // ── NON-VEG ──────────────────────────────────────────────
  {
    id: 6,
    name: "Chicken Biryani",
    category: "nonveg",
    type: "nonveg",
    price: 279,
    originalPrice: 329,
    rating: 4.8,
    reviews: 5632,
    description: "Hyderabadi-style dum biryani made with tender chicken pieces marinated in yoghurt and spices, layered between perfectly cooked saffron-infused basmati rice and sealed with dough.",
    image: "https://images.unsplash.com/photo-1599043513900-ed6fe01d3833?w=400&q=80",
    restaurant: "Biryani Palace",
    time: "35-40",
    tags: ["Bestseller", "#1 Choice"],
    calories: 620,
    badge: "#1 Choice"
  },
  {
    id: 7,
    name: "Butter Chicken",
    category: "nonveg",
    type: "nonveg",
    price: 299,
    originalPrice: 349,
    rating: 4.7,
    reviews: 4201,
    description: "Succulent tandoori chicken pieces simmered in a luscious tomato-butter-cream sauce with gentle spices. A world-famous Indian dish loved for its mild, rich, and velvety gravy.",
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=400&q=80",
    restaurant: "Spice Garden",
    time: "25-30",
    tags: ["Trending", "Creamy"],
    calories: 520,
    badge: "Trending"
  },
  {
    id: 8,
    name: "Grilled Fish Fillet",
    category: "nonveg",
    type: "nonveg",
    price: 349,
    originalPrice: 399,
    rating: 4.5,
    reviews: 876,
    description: "Fresh sea bass fillet seasoned with lemon, herbs, and olive oil, grilled to perfection with a golden crust. Served with seasonal greens, garlic aioli, and lemon wedges.",
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&q=80",
    restaurant: "Sea Bites",
    time: "20-25",
    tags: ["Healthy"],
    calories: 290,
    badge: "Healthy"
  },
  {
    id: 9,
    name: "Mutton Rogan Josh",
    category: "nonveg",
    type: "nonveg",
    price: 399,
    originalPrice: 449,
    rating: 4.6,
    reviews: 1230,
    description: "A Kashmiri masterpiece — slow-cooked tender mutton in an aromatic red gravy made with Kashmiri red chillies, whole spices, yoghurt, and ghee. A true indulgence.",
    image: "https://images.unsplash.com/photo-1545247181-516773cae754?w=400&q=80",
    restaurant: "Kashmir Kitchen",
    time: "40-45",
    tags: ["Chef Special"],
    calories: 580,
    badge: "Chef Special"
  },
  {
    id: 10,
    name: "Prawn Masala",
    category: "nonveg",
    type: "nonveg",
    price: 369,
    originalPrice: 419,
    rating: 4.4,
    reviews: 742,
    description: "Juicy tiger prawns cooked in a spicy, tangy onion-tomato masala with coconut milk, curry leaves, and a hint of tamarind. A coastal delight best enjoyed with steamed rice.",
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80",
    restaurant: "Sea Bites",
    time: "25-30",
    tags: ["Spicy"],
    calories: 360,
    badge: ""
  },

  // ── FAST FOOD ─────────────────────────────────────────────
  {
    id: 11,
    name: "Classic Cheese Burger",
    category: "fastfood",
    type: "nonveg",
    price: 189,
    originalPrice: 219,
    rating: 4.5,
    reviews: 3890,
    description: "A juicy beef patty topped with two slices of melted cheddar, crisp lettuce, ripe tomato, pickles, and our secret smoky sauce — all sandwiched in a toasted brioche bun.",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80",
    restaurant: "Burger Barn",
    time: "15-20",
    tags: ["Bestseller"],
    calories: 540,
    badge: "Bestseller"
  },
  {
    id: 12,
    name: "Loaded Fries",
    category: "fastfood",
    type: "veg",
    price: 149,
    originalPrice: 179,
    rating: 4.3,
    reviews: 2456,
    description: "Crispy golden fries piled high with nacho cheese sauce, jalapeños, sour cream, spring onions, and a dusting of smoked paprika. The ultimate comfort food sharing platter.",
    image: "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=400&q=80",
    restaurant: "Burger Barn",
    time: "10-15",
    tags: ["Must Try"],
    calories: 480,
    badge: "Must Try"
  },
  {
    id: 13,
    name: "Chicken Shawarma",
    category: "fastfood",
    type: "nonveg",
    price: 169,
    originalPrice: 199,
    rating: 4.6,
    reviews: 4123,
    description: "Layers of marinated chicken slow-roasted on a vertical spit, wrapped in a warm pita with creamy garlic sauce, fresh veggies, pickled cucumbers, and a sprinkle of sumac.",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?w=400&q=80",
    restaurant: "Street Eats",
    time: "15-20",
    tags: ["Trending", "Popular"],
    calories: 420,
    badge: "Trending"
  },
  {
    id: 14,
    name: "Crispy Fried Chicken",
    category: "fastfood",
    type: "nonveg",
    price: 219,
    originalPrice: 259,
    rating: 4.5,
    reviews: 3201,
    description: "Tender chicken pieces coated in a crunchy, well-seasoned Southern-style batter, fried to a deep golden crisp. Served with honey mustard dip and coleslaw on the side.",
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=400&q=80",
    restaurant: "KFC Corner",
    time: "15-20",
    tags: ["Crispy"],
    calories: 580,
    badge: ""
  },
  {
    id: 15,
    name: "Club Sandwich",
    category: "fastfood",
    type: "nonveg",
    price: 199,
    originalPrice: 239,
    rating: 4.2,
    reviews: 1120,
    description: "Triple-decker toasted sandwich layered with grilled chicken, crispy bacon, fresh lettuce, tomatoes, hard-boiled egg, and mayo between three slices of white bread.",
    image: "https://images.unsplash.com/photo-1528736235302-52922df5c122?w=400&q=80",
    restaurant: "Cafe Bites",
    time: "10-15",
    tags: [],
    calories: 490,
    badge: ""
  },
  {
    id: 16,
    name: "Peri Peri Wrap",
    category: "fastfood",
    type: "nonveg",
    price: 179,
    originalPrice: 209,
    rating: 4.4,
    reviews: 1876,
    description: "Fiery peri-peri marinated chicken strips with roasted peppers, red onion, rocket leaves, and a cool yoghurt dip, all wrapped in a warm whole-wheat tortilla.",
    image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&q=80",
    restaurant: "Street Eats",
    time: "15-20",
    tags: ["Spicy"],
    calories: 410,
    badge: ""
  },

  // ── DESSERTS ──────────────────────────────────────────────
  {
    id: 17,
    name: "Chocolate Lava Cake",
    category: "desserts",
    type: "veg",
    price: 179,
    originalPrice: 209,
    rating: 4.8,
    reviews: 2890,
    description: "Warm, gooey dark chocolate molten cake with a liquid centre that flows out at the first cut. Served with vanilla ice cream and dusted with icing sugar. Pure indulgence.",
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&q=80",
    restaurant: "Sweet Dreams",
    time: "15-20",
    tags: ["Bestseller", "Indulgent"],
    calories: 380,
    badge: "Bestseller"
  },
  {
    id: 18,
    name: "Mango Cheesecake",
    category: "desserts",
    type: "veg",
    price: 199,
    originalPrice: 229,
    rating: 4.6,
    reviews: 1543,
    description: "Creamy no-bake cheesecake on a buttery biscuit crust, topped with a bright mango coulis and fresh mango chunks. A refreshing tropical dessert perfect for all seasons.",
    image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=400&q=80",
    restaurant: "Sweet Dreams",
    time: "10-15",
    tags: ["Seasonal"],
    calories: 320,
    badge: "Seasonal"
  },
  {
    id: 19,
    name: "Gulab Jamun",
    category: "desserts",
    type: "veg",
    price: 99,
    originalPrice: 129,
    rating: 4.7,
    reviews: 3210,
    description: "Soft, melt-in-the-mouth milk-solid dumplings fried golden and soaked in rose-flavoured sugar syrup. Served warm, garnished with pistachios and saffron strands.",
    image: "https://images.unsplash.com/photo-1666190977278-8c4a2a77f39a?w=400&q=80",
    restaurant: "Mithai Wala",
    time: "10-15",
    tags: ["Classic", "Bestseller"],
    calories: 280,
    badge: "Classic"
  },
  {
    id: 20,
    name: "Belgian Waffle",
    category: "desserts",
    type: "veg",
    price: 149,
    originalPrice: 179,
    rating: 4.5,
    reviews: 2109,
    description: "Crispy, deep-pocketed waffles made fresh to order, served with strawberry compote, a scoop of vanilla ice cream, whipped cream, chocolate drizzle, and a sprinkle of sprinkles.",
    image: "https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=400&q=80",
    restaurant: "Waffle House",
    time: "15-20",
    tags: ["Popular"],
    calories: 540,
    badge: ""
  },

  // ── BEVERAGES ─────────────────────────────────────────────
  {
    id: 21,
    name: "Mango Lassi",
    category: "beverages",
    type: "veg",
    price: 99,
    originalPrice: 129,
    rating: 4.7,
    reviews: 3456,
    description: "Thick, chilled yoghurt blended with Alphonso mangoes, a touch of cardamom, and a kiss of rose water. Topped with dry fruits. The ultimate Indian summer cooler.",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&q=80",
    restaurant: "Cool Sips",
    time: "5-10",
    tags: ["Refreshing"],
    calories: 220,
    badge: "Refreshing"
  },
  {
    id: 22,
    name: "Cold Coffee Frappe",
    category: "beverages",
    type: "veg",
    price: 129,
    originalPrice: 159,
    rating: 4.5,
    reviews: 2234,
    description: "Double-shot espresso blended with full-cream milk, vanilla ice cream, and ice to create a thick, frothy frappe. Topped with whipped cream and a dusting of cocoa powder.",
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&q=80",
    restaurant: "Coffee Corner",
    time: "5-10",
    tags: ["Chilled"],
    calories: 310,
    badge: ""
  },
  {
    id: 23,
    name: "Fresh Lime Soda",
    category: "beverages",
    type: "veg",
    price: 69,
    originalPrice: 89,
    rating: 4.3,
    reviews: 1890,
    description: "Zingy fresh lime juice mixed with sparkling soda water, a pinch of black salt, cumin powder, and mint leaves. Served over crushed ice — the perfect thirst quencher.",
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=400&q=80",
    restaurant: "Cool Sips",
    time: "5-10",
    tags: ["Light", "Healthy"],
    calories: 45,
    badge: "Healthy"
  },
  {
    id: 24,
    name: "Masala Chai",
    category: "beverages",
    type: "veg",
    price: 49,
    originalPrice: 69,
    rating: 4.6,
    reviews: 4201,
    description: "Powerful brewed Indian tea made by simmering ginger, cardamom, cinnamon, cloves, and black pepper with full-fat milk and Assam tea leaves. Sweetened to your preference.",
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",
    restaurant: "Chai Tapri",
    time: "5-10",
    tags: ["Classic"],
    calories: 80,
    badge: "Classic"
  },
  {
    id: 25,
    name: "Strawberry Smoothie",
    category: "beverages",
    type: "veg",
    price: 119,
    originalPrice: 149,
    rating: 4.4,
    reviews: 1340,
    description: "Fresh strawberries blended with chilled yoghurt, honey, and a squeeze of lemon into a silky smooth drink. Packed with antioxidants and bursting with natural berry flavour.",
    image: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=400&q=80",
    restaurant: "Cool Sips",
    time: "5-10",
    tags: ["Healthy"],
    calories: 160,
    badge: "Healthy"
  }
];

const OFFER_BANNERS = [
  {
    id: 1,
    title: "50% OFF up to ₹100",
    subtitle: "Use code YUPP50",
    color: "#ff6b35",
    icon: "🔥"
  },
  {
    id: 2,
    title: "Free Delivery",
    subtitle: "On orders above ₹299",
    color: "#6c5ce7",
    icon: "🚀"
  },
  {
    id: 3,
    title: "New User Special",
    subtitle: "60% OFF on your first order",
    color: "#00b894",
    icon: "🎉"
  },
  {
    id: 4,
    title: "Weekend Fiesta",
    subtitle: "Extra 20% off on weekends",
    color: "#e17055",
    icon: "🎊"
  }
];

const COUPON_CODES = {
  "SAVE10":  { type: "percent", value: 10,  label: "10% off" },
  "YUPP50":  { type: "flat",    value: 50,  label: "Flat ₹50 off" },
  "FIRST60": { type: "percent", value: 60,  label: "60% off (max ₹150)", max: 150 },
  "FREEBIE": { type: "flat",    value: 30,  label: "Flat ₹30 off" },
};

// Export for module use (fallback for non-module scripts)
if (typeof module !== "undefined") {
  module.exports = { FOOD_ITEMS, CATEGORIES, OFFER_BANNERS, COUPON_CODES };
}
